# ----------------------------------------------------------------------------
#
# Package             : jicofo
# Source Repo         : https://github.com/jitsi/jicofo
# Travis Job Link     : https://travis-ci.com/github/asellappen/jicofo/
# Created travis.yml  : Yes
# Maintainer          : Arumugam N S <asellappen@yahoo.com>/Priya Seth<sethp@us.ibm.com>
#
# Script License      : Apache License, Version 2 or later
#
# ----------------------------------------------------------------------------
language: java

jdk:
  - openjdk11
  - openjdk15
  
sudo: True

dist : focal

arch:
  - amd64
  - ppc64le

before_install: 
  - mkdir -p /opt/maven
  - curl https://downloads.apache.org/maven/maven-3/3.6.3/binaries/apache-maven-3.6.3-bin.tar.gz|tar -xz --strip 1 -C /opt/maven
  - export MAVEN_HOME=/opt/maven
  - export PATH=${MAVEN_HOME}/bin:${PATH}

script:
  - if [[ "$TRAVIS_CPU_ARCH" == "ppc64le" ]]; then 
        mvn test ;
    else
        #known issue : jitsi/jicofo#581 for mvn failure for ppc64le
        mvn test  -Dmaven.test.failure.ignore=true;
    fi
